services:
  snakemake_psi4:
    attach: true
    image: ubchemica/psi4-docker-utils:snakemake-1.9.x
    volumes:
      - .:/home/ubuntu/work/
      - ./psi4/:/home/ubuntu/psi4/
      - ./build/:/home/ubuntu/build/
    command: ["./exec.sh"]

